### ISSUE TITLE
ClipboardConnect can't load with Paper paper-1.20.4-361

### ISSUE THREAD

**Issue by Leahcimkrob** [IntellectualSites/ClipboardConnect#31]
### Expected behavior

We will use Clipboardconnect.

### Actual behavior

We get following Error in Console. After this, the server will chrash

### Steps to reproduce

start paper for MC 1.20.4 with CC.

### Plugin and Datapack List

[04:57:17 INFO]: Server Plugins (104):
[04:57:17 INFO]: Paper Plugins:
[04:57:17 INFO]:  - HuskHomes, MarriageMaster, Minepacks, TreasureMapsPlus
[04:57:17 INFO]: Bukkit Plugins:
[04:57:17 INFO]:  - AdvancedChests, AdvancedRegionMarket, AdventCalendar, AdventCore, AntiMapCopy, antiRedstoneClock, AntiSmithingCopy, ArmorStandTools, AuctionHouse, *Automessage
[04:57:17 INFO]:  Bank, *BCommons, BetterConcrete, BigDoors, Booster, BottledExp, Builders-Utilities, BungeeTokens-Spigot, ChatFeelings, ChatFree
[04:57:17 INFO]:  ChestCommands, Citizens, ClearLag, CMI, CMILib, Core, CoreProtect, CraftingStore, Craftmatic, CrashAPI
[04:57:17 INFO]:  CrazyCrates, DeathCoordinates, *DisableChorusFruit, DisableRecipe, Elevator, EmployMe, EnchantmentSolution, *EpicSign, EscoVotifier-Spigot, ESWGFlags
[04:57:17 INFO]:  Ethria-Board, Ethria-Common, EthriaEvent, FancyPerks, FastAsyncWorldEdit, GEmote, GPet, GSit, HeadBlocks, HeadDatabase
[04:57:17 INFO]:  HiddenArmor, HuskHomesGUI, ImageMaps, iShop, ItemSorter, Jobs, KixsChatGames, Lottery, LuckPerms, mcMMO
[04:57:17 INFO]:  MobsToEggs, Multiverse-Core, NBSPlayer, NBTAPI, NoteBlockAPI, NotQuests, PlaceholderAPI, PlayerWarps, PlotBorders, PlotSquared
[04:57:17 INFO]:  PluginManager, PreventMapCloning, ProtocolLib, qsaddon-discount, qsaddon-displaycontrol, qsaddon-list, qscompat-advancedregionmarket, qscompat-plotsquared, QuickShop-Hikari, RankGift
[04:57:17 INFO]:  RankUpgrade, RedisChat, RedLib, Signatures, spark, *Stopwatch, TAB-Bridge, TheCore, UltimateAutoRestart, UltimateBackPack
[04:57:17 INFO]:  UltimateClans, *UltimateSign, UltimateTimber, UltraCosmetics, Vault, ViaBackwards, ViaVersion, Votifier, Werbung, WorldGuard
>

### Paper version

[04:56:30 INFO]: Checking version, please wait...
[04:56:30 INFO]: This server is running Paper version git-Paper-370 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 1fa48d1)
You are running the latest version
Previous version: git-Paper-361 (MC: 1.20.4)

### Plugin version

Will not work, because server crash.

### Other

[04:53:52] [Server thread/ERROR]: Error occurred while enabling ClipboardConnect v1.0.0+241eb59 (Is it up to date?)
dev.derklaro.aerogel.AerogelException: Unable to invoke method private final void net.onelitefeather.clipboardconnect.ClipboardConnect.register(dev.derklaro.aerogel.Injector)
Caused by: dev.derklaro.aerogel.AerogelException: Unable to construct requested value constructor SyncService((Object[])Object)
Caused by: java.lang.NoClassDefFoundError: org/objenesis/strategy/InstantiatorStrategy
	at org.redisson.config.Config.<init>(Config.java:110) ~[?:?]
	at org.redisson.Redisson.<init>(Redisson.java:67) ~[?:?]
	at org.redisson.Redisson.create(Redisson.java:114) ~[?:?]
	at net.onelitefeather.clipboardconnect.services.SyncService.buildRedis(SyncService.kt:107) ~[ClipboardConnect-1.0.0-SNAPSHOT-all.jar:?]
	at net.onelitefeather.clipboardconnect.services.SyncService.<init>(SyncService.kt:54) ~[ClipboardConnect-1.0.0-SNAPSHOT-all.jar:?]
	at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeConstructor(MethodHandleUtil.java:88) ~[?:?]
	at dev.derklaro.aerogel.internal.binding.constructors.ConstructingBindingConstructor.lambda$constructProvider$0(ConstructingBindingConstructor.java:92) ~[?:?]
	at dev.derklaro.aerogel.internal.provider.FunctionalContextualProvider.get(FunctionalContextualProvider.java:74) ~[?:?]
	at dev.derklaro.aerogel.util.Scopes$SingletonContextualProvider.get(Scopes.java:96) ~[?:?]
	at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.resolveInstance(DefaultInjectionContext.java:388) ~[?:?]
	at dev.derklaro.aerogel.internal.invoke.ParameterHelper.lambda$constructParameterSuppliers$3(ParameterHelper.java:95) ~[?:?]
	at dev.derklaro.aerogel.internal.invoke.ParameterHelper.lambda$constructParameterSuppliers$4(ParameterHelper.java:108) ~[?:?]
	at dev.derklaro.aerogel.internal.binding.constructors.ConstructingBindingConstructor.lambda$constructProvider$0(ConstructingBindingConstructor.java:91) ~[?:?]
	at dev.derklaro.aerogel.internal.provider.FunctionalContextualProvider.get(FunctionalContextualProvider.java:74) ~[?:?]
	at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.resolveInstance(DefaultInjectionContext.java:388) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:95) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:79) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:63) ~[?:?]
	at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:139) ~[?:?]
	at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:121) ~[?:?]
	at net.onelitefeather.clipboardconnect.ClipboardConnect.register(ClipboardConnect.kt:140) ~[ClipboardConnect-1.0.0-SNAPSHOT-all.jar:?]
	at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeMethod(MethodHandleUtil.java:71) ~[?:?]
	at dev.derklaro.aerogel.internal.member.DefaultMemberInjector$InjectableMethod.invoke(DefaultMemberInjector.java:584) ~[?:?]
	at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectMethod(DefaultMemberInjector.java:371) ~[?:?]
	at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectInstanceMethods(DefaultMemberInjector.java:330) ~[?:?]
	at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.inject(DefaultMemberInjector.java:166) ~[?:?]
	at dev.derklaro.aerogel.internal.context.MemberInjectionRequest.executeMemberInjection(MemberInjectionRequest.java:73) ~[?:?]
	at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.finishConstruction(DefaultInjectionContext.java:527) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:100) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:79) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:63) ~[?:?]
	at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:139) ~[?:?]
	at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:121) ~[?:?]
	at net.onelitefeather.clipboardconnect.ClipboardConnect.onEnable(ClipboardConnect.kt:73) ~[ClipboardConnect-1.0.0-SNAPSHOT-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-370]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-370]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.objenesis.strategy.InstantiatorStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.redisson.config.Config.<init>(Config.java:110) ~[?:?]
	at org.redisson.Redisson.<init>(Redisson.java:67) ~[?:?]
	at org.redisson.Redisson.create(Redisson.java:114) ~[?:?]
	at net.onelitefeather.clipboardconnect.services.SyncService.buildRedis(SyncService.kt:107) ~[ClipboardConnect-1.0.0-SNAPSHOT-all.jar:?]
	at net.onelitefeather.clipboardconnect.services.SyncService.<init>(SyncService.kt:54) ~[ClipboardConnect-1.0.0-SNAPSHOT-all.jar:?]
	at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeConstructor(MethodHandleUtil.java:88) ~[?:?]
	at dev.derklaro.aerogel.internal.binding.constructors.ConstructingBindingConstructor.lambda$constructProvider$0(ConstructingBindingConstructor.java:92) ~[?:?]
	at dev.derklaro.aerogel.internal.provider.FunctionalContextualProvider.get(FunctionalContextualProvider.java:74) ~[?:?]
	at dev.derklaro.aerogel.util.Scopes$SingletonContextualProvider.get(Scopes.java:96) ~[?:?]
	at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.resolveInstance(DefaultInjectionContext.java:388) ~[?:?]
	at dev.derklaro.aerogel.internal.invoke.ParameterHelper.lambda$constructParameterSuppliers$3(ParameterHelper.java:95) ~[?:?]
	at dev.derklaro.aerogel.internal.invoke.ParameterHelper.lambda$constructParameterSuppliers$4(ParameterHelper.java:108) ~[?:?]
	at dev.derklaro.aerogel.internal.binding.constructors.ConstructingBindingConstructor.lambda$constructProvider$0(ConstructingBindingConstructor.java:91) ~[?:?]
	at dev.derklaro.aerogel.internal.provider.FunctionalContextualProvider.get(FunctionalContextualProvider.java:74) ~[?:?]
	at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.resolveInstance(DefaultInjectionContext.java:388) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:95) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:79) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:63) ~[?:?]
	at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:139) ~[?:?]
	at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:121) ~[?:?]
	at net.onelitefeather.clipboardconnect.ClipboardConnect.register(ClipboardConnect.kt:140) ~[ClipboardConnect-1.0.0-SNAPSHOT-all.jar:?]
	at dev.derklaro.aerogel.internal.util.MethodHandleUtil.invokeMethod(MethodHandleUtil.java:71) ~[?:?]
	at dev.derklaro.aerogel.internal.member.DefaultMemberInjector$InjectableMethod.invoke(DefaultMemberInjector.java:584) ~[?:?]
	at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectMethod(DefaultMemberInjector.java:371) ~[?:?]
	at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.injectInstanceMethods(DefaultMemberInjector.java:330) ~[?:?]
	at dev.derklaro.aerogel.internal.member.DefaultMemberInjector.inject(DefaultMemberInjector.java:166) ~[?:?]
	at dev.derklaro.aerogel.internal.context.MemberInjectionRequest.executeMemberInjection(MemberInjectionRequest.java:73) ~[?:?]
	at dev.derklaro.aerogel.internal.context.DefaultInjectionContext.finishConstruction(DefaultInjectionContext.java:527) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstanceAndRemoveContext(ContextInstanceResolveHelper.java:100) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:79) ~[?:?]
	at dev.derklaro.aerogel.internal.context.util.ContextInstanceResolveHelper.resolveInstance(ContextInstanceResolveHelper.java:63) ~[?:?]
	at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:139) ~[?:?]
	at dev.derklaro.aerogel.internal.DefaultInjector.instance(DefaultInjector.java:121) ~[?:?]
	at net.onelitefeather.clipboardconnect.ClipboardConnect.onEnable(ClipboardConnect.kt:73) ~[ClipboardConnect-1.0.0-SNAPSHOT-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-370]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-370]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:53:52] [Server thread/INFO]: [ClipboardConnect] Disabling ClipboardConnect v1.0.0+241eb59

**Comment by OneLiteFeather** [comment]
This issue is paper version based (never happened before 1.20.4) somehow as far as @TheMeinerLP and I discussed, we have to look into that deeper how to fix it. Hang in there and thanks for your issue :)

**Comment by TheMeinerLP** [comment]
Blocked by: https://github.com/PaperMC/Paper/issues/10116

**Comment by TheMeinerLP** [comment]
Fixes https://github.com/PaperMC/Paper/pull/10117
